#! /bin/sh

#Авто старт 
sxhkd &
picom --config ~/.config/picom/picom.conf &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar
feh --bg-fill "/home/stu/Downloads/beach-edited.jpg"
~/.xprofile 

#GTK
export GTK_THEME=Qogir-dark  

#Cursor
export XCURSOR_THEME=Sunity-cursors
export XCURSOR_SIZE=22
